### ISSUE TITLE
mecab buffer size

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#60] opened 2017-02-21 05:43 UTC
The following returns a server error; pipeline Server - Internal Error [500]
```
curl -s "http://localhost:8080/annotate?outputFormat=json&annotators=ssplit%2Cmecab%2Ccabocha" --data "　米議会上院は１７日、オクラホマ州司法長官のスコット・プルイット氏（４８）を環境保護局（ＥＰＡ）長官とする人事案を賛成５２票、反対４６票で承認した。プルイット氏は、オバマ政権の地球温暖化対策などに批判的で、ＥＰＡを相手取り訴訟を繰り返すなど規制反対の急先鋒（きゅうせんぽう）として知られる。米国の環境規制が抜本的に変わる可能性がある。 　プルイット氏は同日、宣誓し就任した。プルイット氏は２０１５年、オバマ政権が温暖化対策の一環として火力発電所から出る二酸化炭素（ＣＯ２）の排出基準を設けたことに反発し、反対する２７州が参加する集団訴訟を起こした中心人物の一人。オバマ氏在任中の規制導入を阻む形となり、反規制派から「功労者」とみられてきた。ＣＯ２や大気汚染物質を出す石炭に厳しかった環境規制について「エネルギーに勝ち組も負け組もない」と見直す方針を示していた。 　米メディアが、プルイット氏を支援する政治団体が化石燃料企業から政治献金を受けていると報じるなど、たびたびエネルギー産業とのつながりを問題視されてきた。民主党議員らは、採決前にプルイット氏が化石燃料企業と交わした電子メールの公表を求めたが実現しなかった。市民団体が地元オクラホマ州の地裁に起こした訴訟に絡み、プルイット氏はメールの公表を命じられているという。環境保護団体がプルイット氏に反対するＥＰＡ元職員らの署名を募ったところ、７７０人以上（１６日現在）が参加するなど「身内」からも反発が強まっている。 　プルイット氏の下で環境規制の見直しが進めば、米国が温暖化対策の新たな国際ルール「パリ協定」で温室効果ガスの削減目標に掲げた「２０２５年に０５年比で２６～２８％減」は達成できなくなる可能性が高い。中国に続く排出国である米国が対策に消極的な姿勢に転じれば、各国による取り組みにも影響がでそうだ。（ボストン＝ 小林哲 ）"
```

If I remove the `cabocha` annotators, I get the desired output, suggesting this is an issue this annotator. 

Reducing the original document size (remove half of the characters), and then including `cabocha` annotator, desired output is obtained.

I have seen this problem before with `mecab/cabocha` - could this be related to the problem with the buffer size perhaps? How can i alter this value in the Jigg framework?
```
http://localhost:8080/help/mecab
 -b, --input-buffer-size=INT    set input buffer size (default 8192)
```

The response from the server is as below;
```
[ERROR] [02/21/2017 15:16:20.754] [jigg-server-akka.actor.default-dispatcher-245] [akka.actor.ActorSystemImpl(jigg-server)] Error during processing of request: 'null'. Completing with 500 Internal Server Error response.
```

**Comment by hiroshinoji** [comment] 2017-02-21 07:03
Sorry it seems that the cause is in parallel annotation. Temporarily it can be avoided by setting `nThreads=1`. I will investigate the issue.

**Comment by hiroshinoji** [comment] 2017-04-24 08:02
Resolved in the latest develop.

**Closed as completed by hiroshinoji** 2017-04-24 08:02 UTC
